# Generated by Django 5.2.7 on 2025-11-04
from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Enunciado de la pregunta', max_length=500)),
                ('tipo', models.CharField(choices=[('multiple', 'Opción Múltiple'), ('verdadero_falso', 'Verdadero/Falso'), ('texto', 'Texto Corto')], default='multiple', max_length=20)),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('media', 'Media'), ('dificil', 'Difícil')], default='media', max_length=10)),
                ('tema', models.CharField(blank=True, help_text='Tema o categoría', max_length=100)),
                ('opcion_a', models.CharField(blank=True, max_length=300)),
                ('opcion_b', models.CharField(blank=True, max_length=300)),
                ('opcion_c', models.CharField(blank=True, max_length=300)),
                ('opcion_d', models.CharField(blank=True, max_length=300)),
                ('respuesta_correcta', models.CharField(help_text='Respuesta correcta o letra (A, B, C, D)', max_length=300)),
                ('explicacion', models.TextField(blank=True, help_text='Explicación de la respuesta')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tiempo_limite', models.IntegerField(default=30, help_text='Tiempo en minutos')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.CreateModel(
            name='IntentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('puntuacion', models.FloatField(default=0.0)),
                ('total_preguntas', models.IntegerField(default=0)),
                ('respuestas_correctas', models.IntegerField(default=0)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_test', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='boards.test')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
                'verbose_name': 'Intento de Test',
                'verbose_name_plural': 'Intentos de Tests',
            },
        ),
        migrations.CreateModel(
            name='RespuestaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=300)),
                ('es_correcta', models.BooleanField(default=False)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='boards.intenttest')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.question')),
            ],
            options={
                'ordering': ['fecha_respuesta'],
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='preguntas',
            field=models.ManyToManyField(related_name='tests', to='boards.question'),
        ),
    ]
