# Generated by Django 5.2.7 on 2025-11-04 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('pregunta_id', models.IntegerField(db_column='Pregunta_ID', primary_key=True, serialize=False)),
                ('tema', models.CharField(db_column='Tema', max_length=100)),
                ('enunciado', models.TextField(db_column='Enunciado')),
                ('dificultad', models.CharField(choices=[('Facil', 'Fácil'), ('Media', 'Media'), ('Dificil', 'Difícil')], db_column='Dificultad', max_length=20)),
                ('puntuacion', models.IntegerField(db_column='Puntuacion')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'db_table': 'Pregunta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('tema_id', models.CharField(db_column='Tema_ID', max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'db_table': 'Tema',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='respuestaalumno',
            name='pregunta',
            field=models.ForeignKey(db_column='pregunta_id', on_delete=django.db.models.deletion.CASCADE, to='boards.pregunta'),
        ),
        migrations.AlterField(
            model_name='test',
            name='preguntas',
            field=models.ManyToManyField(related_name='tests', to='boards.pregunta'),
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_id', models.IntegerField(db_column='Respuesta_ID')),
                ('pregunta_id', models.IntegerField(db_column='Pregunta_ID')),
                ('solucion', models.CharField(choices=[('Correcta', 'Correcta'), ('Incorrecta', 'Incorrecta')], db_column='Solucion', max_length=20)),
                ('contenido', models.TextField(db_column='Contenido')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'db_table': 'Respuesta',
                'managed': True,
                'unique_together': {('respuesta_id', 'pregunta_id')},
            },
        ),
    ]
