# Generated by Django 5.2.7 on 2025-11-04 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_pregunta_tema_alter_respuestaalumno_pregunta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['tema', '-fecha_creacion'], 'verbose_name': 'Test', 'verbose_name_plural': 'Tests'},
        ),
        migrations.AddField(
            model_name='test',
            name='tema',
            field=models.ForeignKey(blank=True, db_column='tema_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='boards.tema'),
        ),
        migrations.AddField(
            model_name='test',
            name='visible_alumnos',
            field=models.BooleanField(default=False, help_text='¿Visible para los alumnos?'),
        ),
        migrations.AlterField(
            model_name='test',
            name='preguntas',
            field=models.ManyToManyField(blank=True, related_name='tests', to='boards.pregunta'),
        ),
        migrations.CreateModel(
            name='ProgresoTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_preguntas', models.IntegerField(default=0)),
                ('preguntas_respondidas', models.IntegerField(default=0)),
                ('preguntas_correctas', models.IntegerField(default=0)),
                ('porcentaje_completado', models.FloatField(default=0.0)),
                ('porcentaje_aciertos', models.FloatField(default=0.0)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actividad', models.DateTimeField(auto_now=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_temas', to=settings.AUTH_USER_MODEL)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='boards.tema')),
            ],
            options={
                'verbose_name': 'Progreso de Tema',
                'verbose_name_plural': 'Progresos de Temas',
                'ordering': ['alumno', 'tema'],
                'unique_together': {('alumno', 'tema')},
            },
        ),
    ]
