# Generated by Django 5.2.7 on 2025-11-04 15:36

from django.db import migrations


def fix_m2m_table(apps, schema_editor):
    """Corrige la tabla intermedia de Test-Pregunta"""
    with schema_editor.connection.cursor() as cursor:
        # Obtener el tipo de la columna id de boards_test
        cursor.execute("""
            SELECT DATA_TYPE, COLUMN_TYPE
            FROM information_schema.columns
            WHERE table_schema = DATABASE()
            AND table_name = 'boards_test'
            AND column_name = 'id'
        """)
        result = cursor.fetchone()
        id_type = result[1] if result else 'BIGINT'
        
        # Eliminar la tabla intermedia antigua si existe
        cursor.execute("DROP TABLE IF EXISTS boards_test_preguntas")
        
        # Crear la nueva tabla intermedia con el tipo correcto
        cursor.execute(f"""
            CREATE TABLE boards_test_preguntas (
                id {id_type} AUTO_INCREMENT PRIMARY KEY,
                test_id {id_type} NOT NULL,
                pregunta_id INT NOT NULL,
                UNIQUE KEY boards_test_preguntas_test_id_pregunta_id (test_id, pregunta_id),
                CONSTRAINT boards_test_preguntas_test_fk 
                    FOREIGN KEY (test_id) REFERENCES boards_test(id) ON DELETE CASCADE,
                CONSTRAINT boards_test_preguntas_pregunta_fk 
                    FOREIGN KEY (pregunta_id) REFERENCES Pregunta(Pregunta_ID) ON DELETE CASCADE
            )
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_test_options_test_tema_test_visible_alumnos_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_m2m_table, migrations.RunPython.noop),
    ]
