# Generated by Django 5.2.7 on 2025-11-04 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20251104_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respuesta',
            options={'managed': False, 'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
