# Generated by Django 5.2.7 on 2025-11-05 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_alter_respuesta_options_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='porcentaje_minimo',
            field=models.FloatField(default=70.0, help_text='Porcentaje mínimo requerido en el test requisito'),
        ),
        migrations.AddField(
            model_name='test',
            name='test_requisito',
            field=models.ForeignKey(blank=True, help_text='Test que debe superarse antes de poder hacer este', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_desbloqueados', to='boards.test'),
        ),
    ]
