# Generated by Django 5.2.7 on 2025-11-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_test_porcentaje_minimo_test_test_requisito'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='nivel',
            field=models.CharField(choices=[('Facil', 'Fácil'), ('Media', 'Intermedio'), ('Dificil', 'Difícil')], default='Facil', help_text='Nivel de dificultad del test', max_length=20),
        ),
    ]
