# Generated by Django 5.2.7 on 2025-11-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_test_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='visible_profesor',
            field=models.BooleanField(default=True, help_text='¿Visible para el profesor en modo alumno? (para pruebas)'),
        ),
    ]
