# Generated by Django 5.2.7 on 2025-11-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_test_visible_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='disponible_alumno',
            field=models.BooleanField(default=True, help_text='¿Disponible para alumnos? (debe estar visible también)'),
        ),
        migrations.AddField(
            model_name='test',
            name='disponible_profesor',
            field=models.BooleanField(default=True, help_text='¿Disponible para profesor? (debe estar visible también)'),
        ),
    ]
