# Generated by Django 5.2.7 on 2025-11-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_test_disponible_alumno_test_disponible_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='activo',
            field=models.BooleanField(default=True, help_text='¿Tema activo en el sistema?'),
        ),
        migrations.AddField(
            model_name='tema',
            name='disponible_alumno',
            field=models.BooleanField(default=True, help_text='¿Disponible para alumnos?'),
        ),
        migrations.AddField(
            model_name='tema',
            name='disponible_profesor',
            field=models.BooleanField(default=True, help_text='¿Disponible para profesor?'),
        ),
        migrations.AddField(
            model_name='tema',
            name='visible_alumnos',
            field=models.BooleanField(default=True, help_text='¿Visible para los alumnos?'),
        ),
        migrations.AddField(
            model_name='tema',
            name='visible_profesor',
            field=models.BooleanField(default=True, help_text='¿Visible para el profesor en modo alumno?'),
        ),
    ]
