# Generated by Django 5.2.7 on 2025-11-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_tema_activo_tema_disponible_alumno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intenttest',
            name='es_examen',
            field=models.BooleanField(default=False, help_text='¿Es un examen con preguntas aleatorias?'),
        ),
    ]
