# Generated by Django 5.2.7 on 2025-11-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_intenttest_es_examen'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaalumno',
            name='confirmada',
            field=models.BooleanField(default=False),
        ),
    ]
