# Generated by Django 5.2.7 on 2025-11-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_respuestaalumno_confirmada'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='configuracion_aleatoria',
            field=models.JSONField(blank=True, help_text='Configuración del examen aleatorio: temas y número de preguntas', null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='es_aleatorio',
            field=models.BooleanField(default=False, help_text='¿Es un examen con preguntas aleatorias?'),
        ),
    ]
