# Generated by Django 5.2.7 on 2025-11-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='clase',
            field=models.CharField(blank=True, help_text='Clase o grupo del alumno', max_length=50, null=True),
        ),
    ]
