"""
Django settings for StepUp project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from dotenv import load_dotenv

load_dotenv()

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'dev-secret-key-change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Apps locales
    'boards',
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stepup_config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'users' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'stepup_config.settings.theme_context',  # Contexto de tema
            ],
        },
    },
]

WSGI_APPLICATION = 'stepup_config.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Additional locations of static files
STATICFILES_DIRS = [
    BASE_DIR / 'users' / 'static',
]

# Media files (user-uploaded / project assets outside staticfiles)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR.parent / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de autenticación
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Configuración de Email
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'mi.santamaria@upm.es')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'mi.santamaria@upm.es')
SERVER_EMAIL = os.getenv('SERVER_EMAIL', 'mi.santamaria@upm.es')


# ==================== CONFIGURACIÓN DE TEMA Y COLORES ====================
# Paleta de colores basada en la guía de estilo de ETSISI-UPM

THEME_COLORS = {
    # Colores principales (azules ETSISI)
    'primary': '#003366',           # Azul oscuro principal (antes era #003d6b)
    'primary_medium': '#005B99',    # Azul medio
    'primary_light': '#0077c8',     # Azul claro
    
    # Colores de texto
    'text_active': '#787878',       # Texto activo (gris medio)
    'text_inactive': '#999999',     # Texto inactivo (gris claro)
    
    # Colores de fondo
    'bg_normal': '#FFFFFF',         # Fondo normal (blanco)
    'bg_inactive_light': '#A49999', # Fondo inactivo claro (gris)
    'bg_medium': '#005B99',         # Fondo azul medio
    'bg_dark': '#003366',           # Fondo azul oscuro
    
    # Colores para header con gradiente
    'header_gradient_start': '#003d6b',  # Inicio del gradiente del header
    'header_gradient_end': '#004a7f',    # Fin del gradiente del header
    
    # Colores para logo
    'logo_bg_overlay_start': 'rgba(255,255,255,1)',   # Inicio gradiente logo (más opaco)
    'logo_bg_overlay_end': 'rgba(255,255,255,0.6)',     # Fin gradiente logo (más opaco)
    'logo_border': 'rgba(255,255,255,0.3)',             # Borde del logo (más visible)
    
    # Colores de estado
    'success': '#28a745',           # Verde para éxito
    'warning': '#ffc107',           # Amarillo para advertencia
    'danger': '#dc3545',            # Rojo para peligro/error
    'info': '#17a2b8',              # Cyan para información
    
    # Colores de botones
    'btn_inactive_text': '#626262', # Texto botón inactivo
    'btn_inactive_bg': '#678CA6',   # Fondo botón inactivo
}

# Configuración de tipografía
THEME_TYPOGRAPHY = {
    'font_family': 'Oswald-Regular.ttf',  # Fuente principal
    'font_size_base': 64,                  # Tamaño base
}

# Hacer los colores disponibles en templates
def theme_context(request):
    return {
        'THEME_COLORS': THEME_COLORS,
        'THEME_TYPOGRAPHY': THEME_TYPOGRAPHY,
    }
